Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.customize ["modifyvm", :id, "--natpf1", "guestapache,tcp,,8080,,80"]
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo 'vagrant:vagrant' | chpasswd
    sudo apt-get update
    sudo apt-get install -y ufw
    sudo ufw allow 80
    sudo ufw allow 8080
    sudo ufw --force enable
    sudo apt-get -y install apache2
    sudo apt-get install libapache2-mod-proxy-html
    sudo apt-get install libxml2-dev
    sudo a2enmod proxy
    sudo a2enmod proxy_html
    sudo a2enmod proxy_http
    echo 'ProxyPass / http://localhost:8080/' >> /etc/apache2/sites-available/000-default.conf
    sudo service apache2 restart
  SHELL
end